stages:
- build
- test
- deploy
- Trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEPLOY_VARIABLE: "nightly"
  MINICONDA_VERSION: "latest"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /master/
      variables:
        DEPLOY_VARIABLE: "main"  # Override globally-defined DEPLOY_VARIABLE
    - when: always               # Run the pipeline in other cases


build:linux:
  image: continuumio/miniconda3:latest
  stage: build
  tags:
    - linux
  before_script:
    - apt update -yq && apt -yq install build-essential
  script:
    - echo "I am the build stage."
    - source activate base
    - conda install mamba boa conda-verify -c conda-forge
    - |
      conda config --add channels salilab
      conda config --add channels tpeulen
      conda config --add channels tpeulen/label/nightly
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

test:linux:
  image: continuumio/miniconda3:latest
  stage: test
  tags:
    - linux
  variables:
    MINICONDA_OS: "Linux"
  script:
    - echo "I am a test stage job."
    - source activate base
    - conda config --set always_yes yes --set changeps1 no
    - conda install mamba git git-lfs cmake -c conda-forge
    - |
      conda config --add channels salilab
      conda config --add channels tpeulen
      conda config --add channels tpeulen/label/nightly
      conda config --add channels "file://`pwd`/bld-dir"
    - git clone https://gitlab.peulen.xyz/tpeulen/tttr-data --depth 1
    - mamba create -n test python=3.8
    - conda activate test
    - mamba install tttrlib nose scipy
    - |
      cd test
      nosetests

deploy:
  image: continuumio/miniconda3:latest
  stage: deploy
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - echo "I am a depolyment stage job."
    - source activate base
    - conda install anaconda-client
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_VARIABLE} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2


# Downstream projects
TTTRConvert:
  stage: Trigger-cross-projects
  trigger: tpeulen/tttrconvert

Fit2X:
  stage: Trigger-cross-projects
  trigger: tpeulen/fit2x

clsmview:
  stage: Trigger-cross-projects
  trigger: tpeulen/clsmview

scikit-fluorescence:
  stage: Trigger-cross-projects
  trigger: tpeulen/scikit-fluorescence